environments:
  - name: Dev
    provisioner: gcp
    iacPolicy: "CC default latest"
    iacRoot: "terraform"

pipelines:
  zephyr-demo-deploy:
    - pipeline-config@1
    - git-clone@1
    - npm-build@1
    - bash@1

applications:
  zpdemo:
    displayName: "Zephyr Demp"
    srcRoot: "."
    pipeline: zephyr-demo-deploy

deployments:
  dev:
    endpoints:
      - zpdemo
    environment:
      name: Dev
    applications:
      zpdemo:
        pipelineInputs:
          git_remote_path: github.com/cldcvr/zephyr-demo
          pipeline_env: '{"ID":"${terraform.bucket.value.id}"}'
          bash_script: "gsutil cp -R dist/* gs://$$ID"
    output:
      app-endpoint:
        command: echo http://storage.cloud.google.com/$$ID/output.html
